### ISSUE TITLE
‏pkg update  ‏pkg upgrade  ‏pkg install git  ‏pkg install python  ‏pkg install python2

### ISSUE THREAD

**Issue by 6sb** [nasirxo/flb2#14]

**Comment by 6sb** [comment]
‏pkg update

‏pkg upgrade

‏pkg install git

‏pkg install python

‏pkg install python2

**Comment by nasirxo** [comment]
Updated Now 
apt install git python3
git clone https://github.com/nasirxo/flb2
cd flb2
python3 flb2.py
