### ISSUE TITLE
git clone https://github.com/nasirxo/flb2


### ISSUE THREAD

**Issue by Moslem46Alrikaby** [nasirxo/flb2#15]
git clone https://github.com/nasirxo/flb2

**Comment by mode5322** [comment]
![image](https://user-images.githubusercontent.com/62867860/147637722-11301b5e-5eae-486c-9519-f9229cd6465a.png)

Plz help me 
Who to fix it?

**Comment by mohamedgsgxoxo** [comment]
لقد تعطلت الاداه الرجاء.  اعاده.  تشغيلها

**Comment by mohamedgsgxoxo** [comment]
🔴 Failed to Fetch....
🔴 Starting Attack.....

[~] Total Accounts : 0
[>]Password To Try On Accounts
~>

ارجو حل هذه المشكله

**Comment by jasmahmad** [comment]
ارجاءاصلاح الأدات

**Comment by nasirxo** [comment]
Updated Now 
apt install git python3
git clone https://github.com/nasirxo/flb2
cd flb2
python3 flb2.py

**Comment by Rizwanhack** [comment]
Nasir Bhai I'd login issue ha 3 Saal sa
