### ISSUE TITLE
The attack fails error

### ISSUE THREAD

**Issue by mohamedgsgxoxo** [nasirxo/flb2#18]
![Screenshot_٢٠٢٢٠٣١٠-٠٥٤٠٠٤_1](https://user-images.githubusercontent.com/101287626/157577841-737694f7-ae7e-435c-90b7-68e113379595.jpg)
🔴 Failed to Fetch....
🔴 Starting Attack.....

[~] Total Accounts : 0
[>]Password To Try On Accounts
~>

**Comment by nasirxo** [comment]
Updated Now 
apt install git python3
git clone https://github.com/nasirxo/flb2
cd flb2
python3 flb2.py
