### ISSUE TITLE
flb2

### ISSUE THREAD

**Issue by mohamedgsgxoxo** [nasirxo/flb2#19]
Hello my brother Nasir Ali. For the idea that the attack failed, please use the tool. Love and respect, brother Nasser Ali
This is the tool name flb2

😭😭😭😭😭😭😭😭😭
😭😭😭😭😭😭😭😭😭

**Comment by nasirxo** [comment]
Updated Now 
apt install git python3
git clone https://github.com/nasirxo/flb2
cd flb2
python3 flb2.py
