### ISSUE TITLE
flb2

### ISSUE THREAD

**Issue by SarahHusseinAhmed99** [nasirxo/flb2#20]
Hello, how are you, my love, my name is Sarah, I want you to update a tool for your flb2 that needs an update, please update it😢😢
![1651678006410](https://user-images.githubusercontent.com/104917484/166715978-e8e410c2-27e4-4456-a890-c74aa5ff1fd6.jpg)

**Comment by sewazgj** [comment]
Write Code Flb2 Please

**Comment by yddyudufufufufyfyf** [comment]
Its shape never happened

**Comment by nasirxo** [comment]
Updated Now 
apt install git python3
git clone https://github.com/nasirxo/flb2
cd flb2
python3 flb2.py
